name: Ruff Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v3
